# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64c210e4bc300b206d4cb3c20aedbea529f2035c697c13c75c3eb97970cc63226d9103adbd09b502eb317a362815c5277602d4b13b2ac34fedabad339e09adb9

test:
  secret_key_base: 7996a12534ce8ae7dd46cd96fdfe4f31b4fb634903083e073f27f7da0da36af0a2e9ea7aef38ebb4982e5e7e8333c974c2a34762d7ac8fbba014997d8baef5b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
